# Generated by Django 5.2.13 on 2026-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="commande",
            name="mode_paiement",
            field=models.CharField(
                choices=[
                    ("livraison", "Paiement à la livraison"),
                    ("carte", "Carte Bancaire"),
                ],
                default="livraison",
                max_length=20,
            ),
        ),
    ]
