# Generated by Django 5.2.13 on 2026-06-11 22:01

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("orders", "0002_commande_mode_paiement"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="DemandeProduit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "nom_produit",
                    models.CharField(
                        max_length=250, verbose_name="Nom / Marque du produit"
                    ),
                ),
                (
                    "lien_yesstyle",
                    models.URLField(
                        help_text="Copiez-collez le lien du produit sur YesStyle",
                        max_length=500,
                        verbose_name="Lien YesStyle",
                    ),
                ),
                (
                    "quantite",
                    models.PositiveIntegerField(default=1, verbose_name="Quantité"),
                ),
                (
                    "options",
                    models.CharField(
                        blank=True,
                        help_text="Ex: Teinte #21, Taille unique, etc.",
                        max_length=200,
                        verbose_name="Teinte / Taille / Options",
                    ),
                ),
                (
                    "nom_client",
                    models.CharField(max_length=100, verbose_name="Votre Nom complet"),
                ),
                (
                    "contact_client",
                    models.CharField(
                        max_length=100, verbose_name="Téléphone / WhatsApp ou Email"
                    ),
                ),
                (
                    "notes",
                    models.TextField(blank=True, verbose_name="Notes additionnelles"),
                ),
                (
                    "statut",
                    models.CharField(
                        choices=[
                            ("recue", "Reçue"),
                            ("commandee", "Commandée sur YesStyle"),
                            ("arrivee_espagne", "Arrivée en Espagne 🇪🇸"),
                            ("en_route_maroc", "En route vers le Maroc 🇲🇦"),
                            ("livree", "Livrée au client"),
                            ("annulee", "Annulée"),
                        ],
                        default="recue",
                        max_length=30,
                    ),
                ),
                ("date_soumission", models.DateTimeField(auto_now_add=True)),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="demandes_produits",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                "verbose_name": "Demande de produit personnalisé",
                "verbose_name_plural": "Demandes de produits personnalisés",
                "ordering": ["-date_soumission"],
            },
        ),
    ]
