# Generated by Django 4.2.9 on 2026-05-12 19:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Categorie",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=100)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField(blank=True)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="categories/"),
                ),
            ],
            options={
                "verbose_name": "Catégorie",
                "verbose_name_plural": "Catégories",
            },
        ),
        migrations.CreateModel(
            name="Produit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("nom", models.CharField(max_length=200)),
                ("slug", models.SlugField(unique=True)),
                ("description", models.TextField()),
                ("prix", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "image",
                    models.ImageField(blank=True, null=True, upload_to="products/"),
                ),
                ("quantite_stock", models.PositiveIntegerField(default=0)),
                ("disponible", models.BooleanField(default=True)),
                ("date_ajout", models.DateTimeField(default=django.utils.timezone.now)),
                ("marque", models.CharField(blank=True, max_length=100)),
                (
                    "ingredients",
                    models.TextField(blank=True, help_text="Ingrédients du produit"),
                ),
                (
                    "type_peau",
                    models.CharField(
                        blank=True,
                        help_text="Types de peau recommandés",
                        max_length=200,
                    ),
                ),
                (
                    "contenance",
                    models.CharField(
                        blank=True, help_text="Ex: 50ml, 150ml", max_length=50
                    ),
                ),
                (
                    "categorie",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="produits",
                        to="products.categorie",
                    ),
                ),
            ],
            options={
                "verbose_name": "Produit",
                "verbose_name_plural": "Produits",
                "ordering": ["-date_ajout"],
            },
        ),
    ]
