# Generated by Django 5.2.13 on 2026-05-29 21:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("products", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="produit",
            name="en_promotion",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="produit",
            name="prix_promotion",
            field=models.DecimalField(
                blank=True, decimal_places=2, max_digits=10, null=True
            ),
        ),
    ]
